name: Build the documentation

on:
  push:
    branch:
      - main

jobs:
  documentation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install mkdocs
        run: pip install mkdocs

      - name: Build the documentation
        run: mkdocs build

      - uses: actions/upload-pages-artifact@v3
        with:
          name: site
          path: site

  github-pages:
    runs-on: ubuntu-latest
    needs: documentation
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/configure-pages@v5

      - uses: actions/deploy-pages@v4
        with:
          artifact_name: site
